### ISSUE TITLE
1.5.23/24 breaks nbdev in multiple places

### ISSUE THREAD

**Issue by jochym** [fastai/fastcore#481]
After changing to 1.5.24 the nbdev workflow with doc broke. After full upgrade the results is as follows (the repo works fine on 1.5.22/2.2.8):
```
$ nbdev_export 
Traceback (most recent call last):
  File "/home/jochym/.conda/envs/dev/bin/nbdev_export", line 8, in <module>
    sys.exit(nbdev_export())
  File "/home/jochym/.conda/envs/dev/lib/python3.9/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/jochym/.conda/envs/dev/lib/python3.9/site-packages/nbdev/doclinks.py", line 121, in nbdev_export
    files = nbglob(path=path, **kwargs)
  File "/home/jochym/.conda/envs/dev/lib/python3.9/site-packages/nbdev/doclinks.py", line 94, in nbglob
    recursive=get_config().recursive
  File "/home/jochym/.conda/envs/dev/lib/python3.9/site-packages/fastcore/foundation.py", line 269, in __getattr__
    def __getattr__(self,k):   return stop(AttributeError(k)) if k=='d' or k not in self.d else self.get(k)
  File "/home/jochym/.conda/envs/dev/lib/python3.9/site-packages/fastcore/basics.py", line 216, in stop
    raise e
AttributeError: recursive
```
For nbdev_docs:
```
$ nbdev_docs 
Traceback (most recent call last):
  File "/home/jochym/.conda/envs/dev/bin/nbdev_docs", line 8, in <module>
    sys.exit(nbdev_quarto())
  File "/home/jochym/.conda/envs/dev/lib/python3.9/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/jochym/.conda/envs/dev/lib/python3.9/site-packages/nbdev/quarto.py", line 259, in nbdev_quarto
    nbdev_sidebar.__wrapped__(path, file_glob=file_glob, **kwargs)
  File "/home/jochym/.conda/envs/dev/lib/python3.9/site-packages/nbdev/quarto.py", line 101, in nbdev_sidebar
    files = nbglob(path, func=_f, skip_folder_re=skip_folder_re, **kwargs).sorted(key=_sort)
  File "/home/jochym/.conda/envs/dev/lib/python3.9/site-packages/nbdev/doclinks.py", line 94, in nbglob
    recursive=get_config().recursive
  File "/home/jochym/.conda/envs/dev/lib/python3.9/site-packages/fastcore/foundation.py", line 269, in __getattr__
    def __getattr__(self,k):   return stop(AttributeError(k)) if k=='d' or k not in self.d else self.get(k)
  File "/home/jochym/.conda/envs/dev/lib/python3.9/site-packages/fastcore/basics.py", line 216, in stop
    raise e
AttributeError: recursive
```
Downgrading nbdev alone fixes export but breaks docs in even stranger ways. 

I was able to restore functionality by pinning fastcore to 1.5.22 which also downgraded nbdev to 2.2.8.

**Comment by seeM** [comment]
This is fixed by https://github.com/fastai/fastcore/pull/482
